-- NOTE:
-- This migration was generated back when the project was using a different SQL dialect.
-- The canonical initial schema for PostgreSQL lives in `prisma/migrations/0_init`.
-- Keeping this migration as a no-op prevents deploy failures due to incompatible types
-- (e.g., DATETIME) while preserving migration history ordering.
